### PR TITLE
Return non-null exit code when parsing fail

### LINKED ISSUE #27: runrestic exit with status code 0 when parsing fails
This makes, for example, systemd thinks everything is okay, when it is not.

```shell
# systemctl  status runrestic
● runrestic.service - runrestic backup
bash-4.2# systemctl status runrestic.service
● runrestic.service - runrestic backup
   Loaded: loaded (/etc/systemd/system/runrestic.service; static; vendor preset: disabled)
   Active: inactive (dead) since Tue 2020-03-10 12:42:04 CET; 2h 5min ago
  Process: 17443 ExecStart=/usr/local/bin/runrestic (code=exited, status=0/SUCCESS)
 Main PID: 17443 (code=exited, status=0/SUCCESS)

Mar 10 12:42:04 myhostname systemd[1]: Starting runrestic backup...
Mar 10 12:42:04 myhostname runrestic[17443]: Problem parsing /etc/runrestic.toml: invalid literal for int() with base 0: '4...r 360)
Mar 10 12:42:04 myhostname systemd[1]: Started runrestic backup.
Hint: Some lines were ellipsized, use -l to show in full.

```

### PR DESCRIPTION
**Pull request by saimonn**
Fix and Closes #27

### CODE REVIEW

**Comment by andreasnuesslein** [comment]
thanks for the PR! :) do you think you could add a test case? that would super cool

**Comment by saimonn** [comment]
I'll try that

**Comment by saimonn** [comment]
The test was already here, it was just expecting a `return None` with broken config.

The longest part was to find how to install deps and test suite, #29 should help future newcommers on this.

**Comment by andreasnuesslein** [comment]
I realized that it's kinda silly to even keep on going on a broken config file. I hope that solution works for you too? 

Thanks a bunch for helping out :)

**Comment by saimonn** [comment]
You're the python expert, thanks for the fix !

**Comment by saimonn** [comment]
Can I kindly ask you to release a new version with theses recent updates ?

**Comment by andreasnuesslein** [comment]
@saimonn  oh sure thing

**Pull request merged**
